### ISSUE TITLE
Shader error on PS4/PS5 builds

### ISSUE THREAD

**Issue by tour1st** [yasirkula/UnityRuntimeInspector#56]
**Description of the bug**

When building on Unity PS4 or PS5, the following error is reported :
`Shader error in 'UI/ColorWheel': Program 'frag', ambiguous call to 'lerp'. Found 91 possible candidates: at line 115 (on ps5_cggc)`

**Reproduction steps**

- Create an empty project in Unity
- Include the UnityRuntimeInspector package
- Select platform PS4 or PS5
- Build the project

**Platform specs**

- Unity version: Unity 2021.3 or later
- Platform: PS4 or PS5
- How did you download the plugin: using Package Manager

**Available fix**

In file ExternalResources/ColorWheel/Visuals/ColorWheelShader.shader file, at line 115,
replace
`fixed4 cBox = lerp(1, _Color, bGrad.x) * bGrad.y;`
by
`fixed4 cBox = lerp(c, _Color, bGrad.x) * bGrad.y;`

Tested on PS4 and PS5 : shader error doesn't show anymore.

**Comment by yasirkula** [comment]
Learnt something new today lol. I've changed the line as `fixed4 cBox = lerp(fixed4(1, 1, 1, 1), _Color, bGrad.x) * bGrad.y;` because in the future, if we modify the value of `c` before reaching this line, then the lerp's result would be affected from this change.

I won't create a new release for this fix alone but it'll be included in the next release.
